version: '3.9'

services:
  barotrauma:
    image: barotrauma
    build:
      context: .
      args:
        STEAM_EPOC:
	UID: ${UID}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - mods:/mods
      - subs:/subs
      - saves:/Multiplayer
      - config:/config
    ports:
      - 27015:27015/udp
      - 27016:27016/udp

volumes:
  mods:
  subs:
  saves:
  config:

