version: '3.9'

services:
  barotrauma:
    user: "${UID}:${GID}"
    image: barotrauma
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - $HOME/barotrauma-server/workshop-mods:/barotrauma/volumes/workshopMods
      - $HOME/barotrauma-server/local-mods:/barotrauma/volumes/localMods
      - $HOME/barotrauma-server/saves:/barotrauma/volumes/Multiplayer
      - $HOME/barotrauma-server/config:/barotrauma/volumes/config
    ports:
      - 27015:27015/udp
      - 27016:27016/udp

volumes:
  workshop-mods:
  local-mods:
  saves:
  config:
