version: '3.9'

services:
  barotrauma:
    image: barotrauma
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    volumes:
      - $HOME/barotrauma-server/mods:/barotrauma/volumes/mods
      - $HOME/barotrauma-server/subs:/barotrauma/volumes/subs
      - $HOME/barotrauma-server/saves:/barotrauma/volumes/Multiplayer
      - $HOME/barotrauma-server/config:/barotrauma/volumes/config
    ports:
      - 27015:27015/udp
      - 27016:27016/udp

volumes:
  mods:
  subs:
  saves:
  config:

